# Generated by Django 5.2.4 on 2025-07-31 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('inactive', 'Inactive')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'debit_card',
            },
        ),
    ]
